// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmyyggfpjfyepyzqdkrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJteXlnZ2ZwamZ5ZXB5enFka3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMzYwNTUsImV4cCI6MjA3MzkxMjA1NX0.YeguGN_IPMX_At1_0Y3LVKpHriPXfRagEqcPn9w8058";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});